# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabs.ui'
#
# Created: Wed Mar 22 11:58:15 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_tab(object):
    def setupUi(self, tab):
        tab.setObjectName(_fromUtf8("tab"))
        tab.resize(688, 1112)
        self.verticalLayout = QtGui.QVBoxLayout(tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.spinBox = QtGui.QSpinBox(tab)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout.addWidget(self.spinBox, 0, 3, 1, 1)
        self.run_tranus_btn = QtGui.QPushButton(tab)
        self.run_tranus_btn.setObjectName(_fromUtf8("run_tranus_btn"))
        self.gridLayout.addWidget(self.run_tranus_btn, 0, 2, 1, 1)
        self.label = QtGui.QLabel(tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_27 = QtGui.QLabel(tab)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_3.addWidget(self.label_27, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 1, 1, 1)
        self.label_28 = QtGui.QLabel(tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_3.addWidget(self.label_28, 0, 0, 1, 1)
        self.checkBox_22 = QtGui.QCheckBox(tab)
        self.checkBox_22.setText(_fromUtf8(""))
        self.checkBox_22.setObjectName(_fromUtf8("checkBox_22"))
        self.gridLayout_3.addWidget(self.checkBox_22, 1, 5, 1, 1)
        self.label_29 = QtGui.QLabel(tab)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_3.addWidget(self.label_29, 7, 0, 1, 1)
        self.checkBox_29 = QtGui.QCheckBox(tab)
        self.checkBox_29.setText(_fromUtf8(""))
        self.checkBox_29.setObjectName(_fromUtf8("checkBox_29"))
        self.gridLayout_3.addWidget(self.checkBox_29, 5, 5, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 6, 1, 1)
        self.checkBox_25 = QtGui.QCheckBox(tab)
        self.checkBox_25.setText(_fromUtf8(""))
        self.checkBox_25.setObjectName(_fromUtf8("checkBox_25"))
        self.gridLayout_3.addWidget(self.checkBox_25, 4, 5, 1, 1)
        self.label_31 = QtGui.QLabel(tab)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_3.addWidget(self.label_31, 8, 0, 1, 1)
        self.checkBox_20 = QtGui.QCheckBox(tab)
        self.checkBox_20.setText(_fromUtf8(""))
        self.checkBox_20.setObjectName(_fromUtf8("checkBox_20"))
        self.gridLayout_3.addWidget(self.checkBox_20, 8, 5, 1, 1)
        self.label_26 = QtGui.QLabel(tab)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_3.addWidget(self.label_26, 5, 0, 1, 1)
        self.checkBox_27 = QtGui.QCheckBox(tab)
        self.checkBox_27.setText(_fromUtf8(""))
        self.checkBox_27.setObjectName(_fromUtf8("checkBox_27"))
        self.gridLayout_3.addWidget(self.checkBox_27, 2, 5, 1, 1)
        self.label_24 = QtGui.QLabel(tab)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_3.addWidget(self.label_24, 3, 0, 1, 1)
        self.checkBox_28 = QtGui.QCheckBox(tab)
        self.checkBox_28.setText(_fromUtf8(""))
        self.checkBox_28.setObjectName(_fromUtf8("checkBox_28"))
        self.gridLayout_3.addWidget(self.checkBox_28, 7, 5, 1, 1)
        self.checkBox_23 = QtGui.QCheckBox(tab)
        self.checkBox_23.setText(_fromUtf8(""))
        self.checkBox_23.setObjectName(_fromUtf8("checkBox_23"))
        self.gridLayout_3.addWidget(self.checkBox_23, 3, 5, 1, 1)
        self.label_34 = QtGui.QLabel(tab)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_3.addWidget(self.label_34, 6, 0, 1, 1)
        self.label_25 = QtGui.QLabel(tab)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_3.addWidget(self.label_25, 4, 0, 1, 1)
        self.label_30 = QtGui.QLabel(tab)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_3.addWidget(self.label_30, 2, 0, 1, 1)
        self.checkBox_30 = QtGui.QCheckBox(tab)
        self.checkBox_30.setText(_fromUtf8(""))
        self.checkBox_30.setObjectName(_fromUtf8("checkBox_30"))
        self.gridLayout_3.addWidget(self.checkBox_30, 6, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_69 = QtGui.QLabel(tab)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.gridLayout_8.addWidget(self.label_69, 8, 0, 1, 1)
        self.checkBox_62 = QtGui.QCheckBox(tab)
        self.checkBox_62.setText(_fromUtf8(""))
        self.checkBox_62.setObjectName(_fromUtf8("checkBox_62"))
        self.gridLayout_8.addWidget(self.checkBox_62, 10, 5, 1, 1)
        self.label_70 = QtGui.QLabel(tab)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.gridLayout_8.addWidget(self.label_70, 3, 0, 1, 1)
        self.label_71 = QtGui.QLabel(tab)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.gridLayout_8.addWidget(self.label_71, 4, 0, 1, 1)
        self.label_72 = QtGui.QLabel(tab)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.gridLayout_8.addWidget(self.label_72, 5, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem3, 1, 1, 1, 1)
        self.checkBox_63 = QtGui.QCheckBox(tab)
        self.checkBox_63.setText(_fromUtf8(""))
        self.checkBox_63.setObjectName(_fromUtf8("checkBox_63"))
        self.gridLayout_8.addWidget(self.checkBox_63, 11, 5, 1, 1)
        self.checkBox_64 = QtGui.QCheckBox(tab)
        self.checkBox_64.setText(_fromUtf8(""))
        self.checkBox_64.setObjectName(_fromUtf8("checkBox_64"))
        self.gridLayout_8.addWidget(self.checkBox_64, 1, 5, 1, 1)
        self.label_73 = QtGui.QLabel(tab)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.gridLayout_8.addWidget(self.label_73, 1, 0, 1, 1)
        self.checkBox_65 = QtGui.QCheckBox(tab)
        self.checkBox_65.setText(_fromUtf8(""))
        self.checkBox_65.setObjectName(_fromUtf8("checkBox_65"))
        self.gridLayout_8.addWidget(self.checkBox_65, 3, 5, 1, 1)
        self.checkBox_66 = QtGui.QCheckBox(tab)
        self.checkBox_66.setText(_fromUtf8(""))
        self.checkBox_66.setObjectName(_fromUtf8("checkBox_66"))
        self.gridLayout_8.addWidget(self.checkBox_66, 7, 5, 1, 1)
        self.checkBox_67 = QtGui.QCheckBox(tab)
        self.checkBox_67.setText(_fromUtf8(""))
        self.checkBox_67.setObjectName(_fromUtf8("checkBox_67"))
        self.gridLayout_8.addWidget(self.checkBox_67, 4, 5, 1, 1)
        self.label_75 = QtGui.QLabel(tab)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.gridLayout_8.addWidget(self.label_75, 9, 0, 1, 1)
        self.label_76 = QtGui.QLabel(tab)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.gridLayout_8.addWidget(self.label_76, 2, 0, 1, 1)
        self.checkBox_68 = QtGui.QCheckBox(tab)
        self.checkBox_68.setText(_fromUtf8(""))
        self.checkBox_68.setObjectName(_fromUtf8("checkBox_68"))
        self.gridLayout_8.addWidget(self.checkBox_68, 8, 5, 1, 1)
        self.checkBox_69 = QtGui.QCheckBox(tab)
        self.checkBox_69.setText(_fromUtf8(""))
        self.checkBox_69.setObjectName(_fromUtf8("checkBox_69"))
        self.gridLayout_8.addWidget(self.checkBox_69, 2, 5, 1, 1)
        self.label_77 = QtGui.QLabel(tab)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.gridLayout_8.addWidget(self.label_77, 10, 0, 1, 1)
        self.checkBox_70 = QtGui.QCheckBox(tab)
        self.checkBox_70.setText(_fromUtf8(""))
        self.checkBox_70.setObjectName(_fromUtf8("checkBox_70"))
        self.gridLayout_8.addWidget(self.checkBox_70, 9, 5, 1, 1)
        self.label_78 = QtGui.QLabel(tab)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.gridLayout_8.addWidget(self.label_78, 11, 0, 1, 1)
        self.checkBox_71 = QtGui.QCheckBox(tab)
        self.checkBox_71.setText(_fromUtf8(""))
        self.checkBox_71.setObjectName(_fromUtf8("checkBox_71"))
        self.gridLayout_8.addWidget(self.checkBox_71, 5, 5, 1, 1)
        self.label_79 = QtGui.QLabel(tab)
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.gridLayout_8.addWidget(self.label_79, 7, 0, 1, 1)
        self.checkBox_72 = QtGui.QCheckBox(tab)
        self.checkBox_72.setText(_fromUtf8(""))
        self.checkBox_72.setObjectName(_fromUtf8("checkBox_72"))
        self.gridLayout_8.addWidget(self.checkBox_72, 6, 5, 1, 1)
        self.label_80 = QtGui.QLabel(tab)
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.gridLayout_8.addWidget(self.label_80, 6, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem4, 1, 6, 1, 1)
        self.label_74 = QtGui.QLabel(tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_74.setFont(font)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.gridLayout_8.addWidget(self.label_74, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_8)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_6 = QtGui.QLabel(tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 14, 0, 1, 1)
        self.label_54 = QtGui.QLabel(tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.gridLayout_5.addWidget(self.label_54, 0, 0, 1, 1)
        self.label_46 = QtGui.QLabel(tab)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_5.addWidget(self.label_46, 8, 0, 1, 1)
        self.checkBox_41 = QtGui.QCheckBox(tab)
        self.checkBox_41.setText(_fromUtf8(""))
        self.checkBox_41.setObjectName(_fromUtf8("checkBox_41"))
        self.gridLayout_5.addWidget(self.checkBox_41, 10, 5, 1, 1)
        self.label_47 = QtGui.QLabel(tab)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_5.addWidget(self.label_47, 3, 0, 1, 1)
        self.label_48 = QtGui.QLabel(tab)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_5.addWidget(self.label_48, 4, 0, 1, 1)
        self.label_49 = QtGui.QLabel(tab)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_5.addWidget(self.label_49, 5, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 1, 1, 1, 1)
        self.checkBox_42 = QtGui.QCheckBox(tab)
        self.checkBox_42.setText(_fromUtf8(""))
        self.checkBox_42.setObjectName(_fromUtf8("checkBox_42"))
        self.gridLayout_5.addWidget(self.checkBox_42, 1, 5, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem6, 1, 6, 1, 1)
        self.checkBox_43 = QtGui.QCheckBox(tab)
        self.checkBox_43.setText(_fromUtf8(""))
        self.checkBox_43.setObjectName(_fromUtf8("checkBox_43"))
        self.gridLayout_5.addWidget(self.checkBox_43, 2, 5, 1, 1)
        self.label_50 = QtGui.QLabel(tab)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_5.addWidget(self.label_50, 10, 0, 1, 1)
        self.checkBox_44 = QtGui.QCheckBox(tab)
        self.checkBox_44.setText(_fromUtf8(""))
        self.checkBox_44.setObjectName(_fromUtf8("checkBox_44"))
        self.gridLayout_5.addWidget(self.checkBox_44, 9, 5, 1, 1)
        self.checkBox_45 = QtGui.QCheckBox(tab)
        self.checkBox_45.setText(_fromUtf8(""))
        self.checkBox_45.setObjectName(_fromUtf8("checkBox_45"))
        self.gridLayout_5.addWidget(self.checkBox_45, 5, 5, 1, 1)
        self.label_51 = QtGui.QLabel(tab)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_5.addWidget(self.label_51, 7, 0, 1, 1)
        self.checkBox_46 = QtGui.QCheckBox(tab)
        self.checkBox_46.setText(_fromUtf8(""))
        self.checkBox_46.setObjectName(_fromUtf8("checkBox_46"))
        self.gridLayout_5.addWidget(self.checkBox_46, 6, 5, 1, 1)
        self.label_52 = QtGui.QLabel(tab)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_5.addWidget(self.label_52, 6, 0, 1, 1)
        self.label_53 = QtGui.QLabel(tab)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout_5.addWidget(self.label_53, 1, 0, 1, 1)
        self.checkBox_47 = QtGui.QCheckBox(tab)
        self.checkBox_47.setText(_fromUtf8(""))
        self.checkBox_47.setObjectName(_fromUtf8("checkBox_47"))
        self.gridLayout_5.addWidget(self.checkBox_47, 3, 5, 1, 1)
        self.checkBox_48 = QtGui.QCheckBox(tab)
        self.checkBox_48.setText(_fromUtf8(""))
        self.checkBox_48.setObjectName(_fromUtf8("checkBox_48"))
        self.gridLayout_5.addWidget(self.checkBox_48, 7, 5, 1, 1)
        self.checkBox_49 = QtGui.QCheckBox(tab)
        self.checkBox_49.setText(_fromUtf8(""))
        self.checkBox_49.setObjectName(_fromUtf8("checkBox_49"))
        self.gridLayout_5.addWidget(self.checkBox_49, 4, 5, 1, 1)
        self.label_55 = QtGui.QLabel(tab)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout_5.addWidget(self.label_55, 9, 0, 1, 1)
        self.label_56 = QtGui.QLabel(tab)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout_5.addWidget(self.label_56, 2, 0, 1, 1)
        self.checkBox_50 = QtGui.QCheckBox(tab)
        self.checkBox_50.setText(_fromUtf8(""))
        self.checkBox_50.setObjectName(_fromUtf8("checkBox_50"))
        self.gridLayout_5.addWidget(self.checkBox_50, 8, 5, 1, 1)
        self.label_3 = QtGui.QLabel(tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 11, 0, 1, 1)
        self.checkBox_4 = QtGui.QCheckBox(tab)
        self.checkBox_4.setText(_fromUtf8(""))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.gridLayout_5.addWidget(self.checkBox_4, 14, 5, 1, 1)
        self.checkBox = QtGui.QCheckBox(tab)
        self.checkBox.setText(_fromUtf8(""))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_5.addWidget(self.checkBox, 11, 5, 1, 1)
        self.label_5 = QtGui.QLabel(tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_5.addWidget(self.label_5, 13, 0, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(tab)
        self.checkBox_2.setText(_fromUtf8(""))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_5.addWidget(self.checkBox_2, 12, 5, 1, 1)
        self.label_4 = QtGui.QLabel(tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_5.addWidget(self.label_4, 12, 0, 1, 1)
        self.checkBox_3 = QtGui.QCheckBox(tab)
        self.checkBox_3.setText(_fromUtf8(""))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridLayout_5.addWidget(self.checkBox_3, 13, 5, 1, 1)
        self.label_7 = QtGui.QLabel(tab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 15, 0, 1, 1)
        self.checkBox_5 = QtGui.QCheckBox(tab)
        self.checkBox_5.setText(_fromUtf8(""))
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.gridLayout_5.addWidget(self.checkBox_5, 15, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.generate_btn = QtGui.QPushButton(tab)
        self.generate_btn.setObjectName(_fromUtf8("generate_btn"))
        self.horizontalLayout.addWidget(self.generate_btn)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.check_all_btn = QtGui.QPushButton(tab)
        self.check_all_btn.setObjectName(_fromUtf8("check_all_btn"))
        self.horizontalLayout.addWidget(self.check_all_btn)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.console = QtGui.QTextBrowser(tab)
        self.console.setObjectName(_fromUtf8("console"))
        self.verticalLayout.addWidget(self.console)

        self.retranslateUi(tab)
        QtCore.QMetaObject.connectSlotsByName(tab)

    def retranslateUi(self, tab):
        tab.setWindowTitle(_translate("tab", "Options TRANUS", None))
        self.run_tranus_btn.setText(_translate("tab", "Run TRANUS", None))
        self.label.setText(_translate("tab", "Run TRANUS to generate the basic files needed for the other operations TRANUS", None))
        self.label_27.setText(_translate("tab", "Run", None))
        self.label_28.setText(_translate("tab", "Imploc", None))
        self.label_29.setText(_translate("tab", "Consumption coefficients by sector", None))
        self.label_31.setText(_translate("tab", "Total consumption by sector and zone", None))
        self.label_26.setText(_translate("tab", "Total production by year/policy", None))
        self.label_24.setText(_translate("tab", "All information, comma-delimited", None))
        self.label_34.setText(_translate("tab", "Internal information by sector and zone", None))
        self.label_25.setText(_translate("tab", "Total production by sector and zone", None))
        self.label_30.setText(_translate("tab", "All information by sector and zone", None))
        self.label_69.setText(_translate("tab", "Link Route & category profile", None))
        self.label_70.setText(_translate("tab", "Cordons (only with IMPTRA.DAT)", None))
        self.label_71.setText(_translate("tab", "Filter links by Demand/Capacity range", None))
        self.label_72.setText(_translate("tab", "Table of indicators", None))
        self.label_73.setText(_translate("tab", "Run", None))
        self.label_75.setText(_translate("tab", "Transit Routes profiles", None))
        self.label_76.setText(_translate("tab", "Report all links", None))
        self.label_77.setText(_translate("tab", "Route profile in comma delimited format", None))
        self.label_78.setText(_translate("tab", "Report specified link types", None))
        self.label_79.setText(_translate("tab", "Report specified links", None))
        self.label_80.setText(_translate("tab", "Indicators in comma delimited format ", None))
        self.label_74.setText(_translate("tab", "Imptra", None))
        self.label_6.setText(_translate("tab", "Exogenous trips by transport category", None))
        self.label_54.setText(_translate("tab", "Mats", None))
        self.label_46.setText(_translate("tab", "Total trips (sum of categories)", None))
        self.label_47.setText(_translate("tab", "Disut. by mode and transport category", None))
        self.label_48.setText(_translate("tab", "Disut. by socio-economic sector", None))
        self.label_49.setText(_translate("tab", "Trips by mode", None))
        self.label_50.setText(_translate("tab", "Flows by socio-economic sector", None))
        self.label_51.setText(_translate("tab", "Trips by mode and transport category", None))
        self.label_52.setText(_translate("tab", "Trips by transport category ", None))
        self.label_53.setText(_translate("tab", "Run", None))
        self.label_55.setText(_translate("tab", "Frequency distribution of trips by mode", None))
        self.label_56.setText(_translate("tab", "Disut. by transport category", None))
        self.label_3.setText(_translate("tab", "Flow by transport category", None))
        self.label_5.setText(_translate("tab", "Costs by socio-economic sector", None))
        self.label_4.setText(_translate("tab", "Costs by transport category", None))
        self.label_7.setText(_translate("tab", "Exogenous trips by category and mode", None))
        self.generate_btn.setText(_translate("tab", "Generate", None))
        self.check_all_btn.setText(_translate("tab", "Check all", None))

